### ISSUE TITLE
ui-bootstrap unexpected directive name

### ISSUE THREAD

**Issue by colinbes** [karma4u101/FoBo#119]
*Using fobo_3.0_2.11 version 1.7 on liftweb 3.0*

When reviewing angular-ui-bootstrap website theor examples show directives like uibAccordionGroup, but in FoBo angular resource I see it as accordionGroup.

Further inspection shows that uibAccordionGroup is in angular-ui-bootstrap but accordionGroup is in FoBo's angular ui resource - this is same for all directives.

Am I missing something?

**Comment by karma4u101** [comment]
Hi Colin 
FoBo contains 3 (older) versions of ui-bootstrap v0.2.0, v0.7.0 and v0.10.0 and I guess you are looking at the current version v2.3.0. It seems they have started to prefix there directive with uib- which is a good idea. 
If you find FoBo useful you might want to consider throw in a PR for the latest angular 1.x ui-bootstrap, in any case I have added a issue #120 for it to be added in FoBo v2.0

**Comment by colinbes** [comment]
Talk about missing the obvious, sorry to have you spend your time on this, I should have seen this, but thanks.
