### ISSUE TITLE
Update Font Awesome to v4.5.0

### ISSUE THREAD

**Issue by yukoff** [karma4u101/FoBo#65]
There are 20 new icons added (personally I'm interested in those for shopping). I'll take a look on this later

**Comment by karma4u101** [comment]
Great if you get time for it ;) One thing that is easy to miss is the font path in the css, take a look at the 4.3.0 css files it's in the top of the files. The rest is FoBo resource plumbing. 

As I am all over the place in the ref_mod branch and I guess you are running the latest snapshots I could actually find a stable point and put in the 4.5.0 FA stuff (later today) and publish new snapshots unless you already have started working on a PR, what ever works best for you?

**Comment by yukoff** [comment]
No, I haven't started yet - it's not that urgent thing ;) Currently I'm drafting a prototype, so I used what esisted for the moment - will get back to this later.

**Comment by karma4u101** [comment]
Understandable, then as I was planing on getting the new FA stuff in to FoBo v1.6 anyway I will take some time to integrate it and when I have a stable point in my re-factoring work I will push new snapshots. I will let you know when it's done.

**Comment by karma4u101** [comment]
@yukoff Now you can use FontAwesome450
via
FoBo.ToolKit.Init=FoBo.ToolKit.FontAwesome450
or 
FoBo.Resource.Init=FoBo.Resource.FontAwesome450

I have published new snapshots
